version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /swift/*
      - /swift/**/*
      - /containers/*
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Berlin
