version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
    assignees:
      - ffried
    reviewers:
      - ffried
  # Use wildcards as soon as available: https://github.com/dependabot/dependabot-core/issues/5137
  - package-ecosystem: "github-actions"
    directory: "/swift/runner-setup-versions"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
    assignees:
      - ffried
    reviewers:
      - ffried
