name: SPM Test Swift Package

on:
  workflow_call:
    inputs:
      os:
        description: The os to use for building. Must be 'macOS' or 'ubuntu'.
        required: true
        type: string
      max-swift-version:
        description: The maximum supported Swift version.
        required: true
        type: string
      swift-version-offset:
        description: The Swift version offset to apply.
        required: true
        type: number
        default: 0
      use-sudo:
        description: Whether to use sudo for running the tests.
        required: false
        type: boolean
        default: false
      container-before-run:
        description: A command to run before the documentation is generated. This is only run if the documentation is generated in a container.
        required: false
        type: string
      skip-codecov:
        description: Whether to skip uploading to codecov.
        required: false
        type: boolean
        default: false
      fail-if-codecov-fails:
        description: Whether to fail if codecov fails.
        required: false
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        description: The token to use for uploading to codecov.
        required: false

permissions:
  contents: read

jobs:
  determine-versions:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      build-os: ${{ steps.builder.outputs.runner-os }}
      build-container: ${{ steps.builder.outputs.container }}
      xcode-version: ${{ steps.builder.outputs.xcode-version }}
    steps:
      - uses: sersoft-gmbh/oss-common-actions/swift/latest-version@main
        id: swift-version
        with:
          max-supported: ${{ inputs.max-swift-version }}
          offset: ${{ inputs.swift-version-offset }}
      - uses: sersoft-gmbh/oss-common-actions/swift/runner-setup-versions@main
        id: builder
        with:
          os: ${{ inputs.os }}
          swift-version: ${{ steps.swift-version.outputs.version }}

  run-tests:
    needs: determine-versions
    runs-on: ${{ needs.determine-versions.outputs.build-os }}
    container: ${{ needs.determine-versions.outputs.build-container }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ runner.os == 'macOS' }}
        with:
          xcode-version: ${{ needs.determine-versions.outputs.xcode-version }}
      - name: Run before command
        if: ${{ runner.os != 'macOS' && inputs.container-before-run != '' }}
        run: ${{ inputs.container-before-run }}
      - uses: sersoft-gmbh/oss-common-actions/swift/test/spm@main
        with:
          use-sudo: ${{ inputs.use-sudo }}
          skip-codecov: ${{ inputs.skip-codecov }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          fail-if-codecov-fails: ${{ inputs.fail-if-codecov-fails }}
