name: Xcode Test Swift Package

on:
  workflow_call:
    inputs:
      xcode-scheme:
        description: The Xcode scheme to test.
        required: true
        type: string
      max-swift-version:
        description: The maximum supported Swift version.
        required: true
        type: string
      swift-version-offset:
        description: The Swift version offset to apply.
        required: true
        type: number
        default: 0
      platform:
        description: The platform to test on.
        required: true
        type: string
      platform-version:
        description: The platform version to test on.
        required: false
        type: string
        default: latest
      before-run:
        description: A command to run before the tests are run. The environment variable `IS_IN_CONTAINER` is set to 1 if the command is run within a container.
        required: false
        type: string
      fail-if-xcode-not-supported:
        description: Whether to fail if the Xcode version is not supported on GH hosted runners.
        required: false
        type: boolean
        default: false
      skip-codecov:
        description: Whether to skip uploading to codecov.
        required: false
        type: boolean
        default: false
      fail-if-codecov-fails:
        description: Whether to fail if codecov fails.
        required: false
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        description: The token to use for uploading to codecov.
        required: false

permissions:
  contents: read

jobs:
  determine-versions:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      build-os: ${{ steps.builder.outputs.runner-os }}
      xcode-version: ${{ steps.builder.outputs.xcode-version }}
      xcode-version-supported: ${{ steps.builder.outputs.xcode-version-supported }}
      remove-package-resolved-file-before-build: ${{ steps.swift-version.outputs.has-breaking-resolved-file-changes }}
    steps:
      - uses: sersoft-gmbh/oss-common-actions/swift/latest-version@main
        id: swift-version
        with:
          max-supported: ${{ inputs.max-swift-version }}
          offset: ${{ inputs.swift-version-offset }}
      - uses: sersoft-gmbh/oss-common-actions/swift/runner-setup-versions@main
        id: builder
        with:
          os: macOS
          swift-version: ${{ steps.swift-version.outputs.version }}

  run-tests:
    needs: determine-versions
    runs-on: ${{ needs.determine-versions.outputs.build-os }}
    steps:
      - name: Run before command
        if: ${{ inputs.before-run != '' }}
        env:
          IS_IN_CONTAINER: 0
        run: ${{ inputs.before-run }}
      - uses: sersoft-gmbh/oss-common-actions/swift/test/xcode@main
        if: ${{ runner.os == 'macOS' && (needs.determine-versions.outputs.xcode-version-supported == 'true' || inputs.fail-if-xcode-not-supported) }}
        with:
          xcode-version: ${{ needs.determine-versions.outputs.xcode-version }}
          delete-package-resolved-file-before-build: ${{ needs.determine-versions.outputs.remove-package-resolved-file-before-build }}
          xcode-scheme: ${{ inputs.xcode-scheme }}
          platform: ${{ inputs.platform }}
          platform-version: ${{ inputs.platform-version }}
          skip-codecov: ${{ inputs.skip-codecov }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          fail-if-codecov-fails: ${{ inputs.fail-if-codecov-fails }}
